apiVersion: v1
kind: Service
metadata:
  name: acm-agent
  namespace: open-cluster-management-agent
  labels:
    app: acm-agent
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 4443
  selector:
    app: acm-agent
