---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acm-agent-sa
  namespace: open-cluster-management-agent

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-agent
rules:
- apiGroups: [""]
  resources: ["configmaps", "events", "endpoints","services"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get"]
- apiGroups: ["config.openshift.io"]
  resources: ["clusterversions"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acm-agent
subjects:
  - kind: ServiceAccount
    name: acm-agent-sa
    namespace: open-cluster-management-agent
