apiVersion: v1
kind: Service
metadata:
  name: acm-agent
  namespace: multicloud-endpoint
  labels:
    app: acm-agent
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 4443
  selector:
    app: acm-agent

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: acm-agent
  namespace: multicloud-endpoint
  labels:
    app: acm-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-agent
  template:
    metadata:
      labels:
        app: acm-agent
    spec:
      serviceAccountName: klusterlet-sa
      containers:
        - name: acm-agent
          image: github.com/open-cluster-management/multicloud-operators-foundation/cmd/acm-agent
          args:
            - "/acm-agent"
            - "--hub-kubeconfig=/var/run/hub/kubeconfig"
            - "--cluster-name=cluster0"
            - "--port=4443"
            - "--klusterlet-address=acm-agent.multicloud-endpoint.svc"
            - "--klusterlet-port=443"
          volumeMounts:
            - name: hub-config
              mountPath: /var/run/hub
      volumes:
        - name: hub-config
          secret:
            secretName: mcm-connmgr-hub-kubeconfig
