kind: Deployment
apiVersion: apps/v1
metadata:
  name: acm-agent
  namespace: multicloud-endpoint
  labels:
    app: acm-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-agent
  template:
    metadata:
      labels:
        app: acm-agent
    spec:
      serviceAccountName: klusterlet-sa
      containers:
        - name: acm-agent
          image: github.com/open-cluster-management/multicloud-operators-foundation/cmd/acm-agent
          args:
            - "/acm-agent"
            - "--hub-kubeconfig=/var/run/hub/kubeconfig"
            - "--cluster-name=cluster0"
          volumeMounts:
            - name: hub-config
              mountPath: /var/run/hub
      volumes:
        - name: hub-config
          secret:
            secretName: hubconfig
