
dist: trusty

os:
  - linux

language: go
go: "1.13.x"

services:
  - docker

# Only build on master, stable branches and tag
# The stable branch and tag should be leading with numbers
branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "GX23KUTS/lIydLqF/10JHjkmQu4wzbM1gqyIZSGKbDqid0/q/fJh6UjP4MVajWdR2Fvqu9R29gvsQd1siRcIILvhBLpb6xjhriTCdvuIN9quy+nUYmOM+8aaHItL7YSBeOru4pXBNuj75xlbz/zOLKBEJ8fbsBaIKplGPm6OateWD6rrmgze1qsXB/rJbGsTOEQds0V2yqGZS7cQCwg2P0rZoS34FM0jNBydu06shNN/RVPQtscrAdyADdAvc6xAZ+kASDowKMsa38/3mkfv+rHq8B/UMba1jpR8k2BjGO6D1klIG6OssoGyarqjjtJvq9GaXEhgDJxO08A3Fr60L8Fc9m0CRg05cpFYg1L4yhhE3I9hTBwRvm4Va5ms2GK4cHaz0N/TE0qQwATxTEtUD4YPb6nImWQEImTnyyTjRhOoaB/c/7HiK2L33y1J/Pc4Gd6WjhScI9ChZ3Y/vp8OlHfg4Yw8rLYJ/T63V4Y/ZliyFbbTRly3fXx1IYuhLbBLCFde3JFQfYQp4Kesp60ultGjinb+K6/XjUnkDCJiVvpTpwzEAnFo3CSzNK7MQCJmpVhsgmSP9UZqxGnslQKdLWQZTvckJVA6yKG+UHhSXsuC9Y1qUhqmUyWKcO+fi09HunGTgFQheOPn6A+myG6JONLsUNU9g02RSFhyygcnFO0="


env:
  global:
    # Required
    - OS=linux

    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_DEPLOY_COMMAND=${TRAVIS_BUILD_DIR}/build/deploy-to-cluster.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  - lint
  - build
  - unit-test
  - test-e2e
  - publish

jobs:
  include:
    - stage: lint
      name: "Run code lint"
      if: type = pull_request
      script: bash ${TRAVIS_BUILD_DIR}/build/run-code-lint.sh
    - stage: build
      name: "Build the image and run unit tests"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make
          make copyright-check TRAVIS_BRANCH=${TRAVIS_BRANCH} TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
          make component/build
          make component/push
          make imagescan/status
          make security/scans
    - stage: unit-test
      name: "Run unit test"
      script:
        # Set the image tag differently for PRs
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        # Bootstrap the build harness, pull test image, and run unit tests.
        - |
          make
          make component/test/unit
          make sonar/go
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      if: type = pull_request
      script:
        #Check out a clusterpool, set up oc, deploy, run e2e tests, and return clusterpool cluster
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make
          make component/pull
          make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - |
          make
          make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
