# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: acm-controller
  namespace: open-cluster-management
  labels:
    app: acm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-controller
  template:
    metadata:
      labels:
        app: acm-controller
    spec:
      serviceAccountName: acm-foundation-sa
      containers:
      - name: acm-controller
        image: ko://github.com/open-cluster-management/multicloud-operators-foundation/cmd/acm-controller
        imagePullPolicy: IfNotPresent
        args:
          - "/acm-controller"
          - "--agent-cafile=/var/run/agent/ca.crt"
          - "--enable-rbac=true"
        volumeMounts:
          - mountPath: /var/run/agent
            name: agent-certs
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
      volumes:
      - name: agent-certs
        secret:
          defaultMode: 420
          secretName: acm-agent-cert
