kind: Deployment
apiVersion: apps/v1
metadata:
  name: acm-proxyserver
  namespace: open-cluster-management
  labels:
    app: acm-proxyserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-proxyserver
  template:
    metadata:
      labels:
        app: acm-proxyserver
    spec:
      serviceAccountName: acm-foundation-sa
      containers:
      - name: acm-proxyserver
        image: ko://github.com/open-cluster-management/multicloud-operators-foundation/cmd/acm-proxyserver
        imagePullPolicy: IfNotPresent
        args:
          - "/acm-proxyserver"
          - "--secure-port=6443"
          - "--tls-cert-file=/var/run/apiserver/tls.crt"
          - "--tls-private-key-file=/var/run/apiserver/tls.key"
          - "--agent-cafile=/var/run/agent/ca.crt"
          - "--agent-certfile=/var/run/agent/tls.crt"
          - "--agent-keyfile=/var/run/agent/tls.key"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
        volumeMounts:
        - mountPath: /var/run/agent
          name: agent-certs
        - mountPath: /var/run/apiserver
          name: apiserver-certs
      volumes:
      - name: agent-certs
        secret:
          defaultMode: 420
          secretName: acm-agent-cert
      - name: apiserver-certs
        secret:
          defaultMode: 420
          secretName: acm-apiserver-cert
