# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcm-controller
  namespace: multicloud-system
  labels:
    app: mcm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcm-controller
  template:
    metadata:
      labels:
        app: mcm-controller
    spec:
      serviceAccountName: hub-sa
      containers:
      - name: mcm-controller
        image: github.com/open-cluster-management/multicloud-operators-foundation/cmd/mcm-controller
        imagePullPolicy: IfNotPresent
        args:
          - "/mcm-controller"
          - "--enable-rbac"
          - "--enable-service-registry"
          - "--enable-inventory"
          - "--leader-elect=true"
